export enum TokenType {
  // Keywords
  SELECT = 'SELECT',
  FROM = 'FROM',
  WHERE = 'WHERE',
  INSERT = 'INSERT',
  INTO = 'INTO',
  UPDATE = 'UPDATE',
  DELETE = 'DELETE',
  CREATE = 'CREATE',
  DROP = 'DROP',
  ALTER = 'ALTER',
  TABLE = 'TABLE',
  ADD = 'ADD',
  COLUMN = 'COLUMN',
  INDEX = 'INDEX',
  JOIN = 'JOIN',
  LEFT = 'LEFT',
  RIGHT = 'RIGHT',
  INNER = 'INNER',
  OUTER = 'OUTER',
  CROSS = 'CROSS',
  ON = 'ON',
  AND = 'AND',
  OR = 'OR',
  NOT = 'NOT',
  IN = 'IN',
  BETWEEN = 'BETWEEN',
  LIKE = 'LIKE',
  IS = 'IS',
  NULL = 'NULL',
  AS = 'AS',
  ORDER = 'ORDER',
  BY = 'BY',
  GROUP = 'GROUP',
  HAVING = 'HAVING',
  LIMIT = 'LIMIT',
  OFFSET = 'OFFSET',
  ASC = 'ASC',
  DESC = 'DESC',
  VALUES = 'VALUES',
  SET = 'SET',
  DISTINCT = 'DISTINCT',
  ALL = 'ALL',
  TRUE = 'TRUE',
  FALSE = 'FALSE',
  IF = 'IF',
  EXISTS = 'EXISTS',
  PRIMARY = 'PRIMARY',
  KEY = 'KEY',
  AUTO_INCREMENT = 'AUTO_INCREMENT',
  UNIQUE = 'UNIQUE',
  DEFAULT = 'DEFAULT',
  REFERENCES = 'REFERENCES',
  FOREIGN = 'FOREIGN',
  CONSTRAINT = 'CONSTRAINT',
  CHECK = 'CHECK',

  // Data types
  INTEGER = 'INTEGER',
  INT = 'INT',
  BIGINT = 'BIGINT',
  SMALLINT = 'SMALLINT',
  TINYINT = 'TINYINT',
  FLOAT = 'FLOAT',
  DOUBLE = 'DOUBLE',
  DECIMAL = 'DECIMAL',
  NUMERIC = 'NUMERIC',
  REAL = 'REAL',
  TEXT = 'TEXT',
  VARCHAR = 'VARCHAR',
  CHAR = 'CHAR',
  BLOB = 'BLOB',
  BOOLEAN = 'BOOLEAN',
  BOOL = 'BOOL',
  DATE = 'DATE',
  TIME = 'TIME',
  DATETIME = 'DATETIME',
  TIMESTAMP = 'TIMESTAMP',

  // Aggregate functions
  COUNT = 'COUNT',
  SUM = 'SUM',
  AVG = 'AVG',
  MIN = 'MIN',
  MAX = 'MAX',

  // Other functions
  COALESCE = 'COALESCE',
  NULLIF = 'NULLIF',
  CASE = 'CASE',
  WHEN = 'WHEN',
  THEN = 'THEN',
  ELSE = 'ELSE',
  END = 'END',
  CAST = 'CAST',
  UPPER = 'UPPER',
  LOWER = 'LOWER',
  LENGTH = 'LENGTH',
  TRIM = 'TRIM',
  SUBSTR = 'SUBSTR',
  SUBSTRING = 'SUBSTRING',
  CONCAT = 'CONCAT',
  REPLACE = 'REPLACE',
  NOW = 'NOW',
  CURRENT_TIMESTAMP = 'CURRENT_TIMESTAMP',
  CURRENT_DATE = 'CURRENT_DATE',
  CURRENT_TIME = 'CURRENT_TIME',

  // Literals
  STRING = 'STRING',
  NUMBER = 'NUMBER',
  IDENTIFIER = 'IDENTIFIER',
  PLACEHOLDER = 'PLACEHOLDER',

  // Operators
  EQUALS = '=',
  NOT_EQUALS = '!=',
  LESS_THAN = '<',
  GREATER_THAN = '>',
  LESS_EQUALS = '<=',
  GREATER_EQUALS = '>=',
  PLUS = '+',
  MINUS = '-',
  MULTIPLY = '*',
  DIVIDE = '/',
  MODULO = '%',
  CONCAT_OP = '||',

  // Punctuation
  COMMA = ',',
  DOT = '.',
  LPAREN = '(',
  RPAREN = ')',
  ASTERISK = '*',
  SEMICOLON = ';',

  // Special
  EOF = 'EOF',
}

export interface Token {
  type: TokenType;
  value: string;
  line: number;
  column: number;
}

export const KEYWORDS: Record<string, TokenType> = {
  SELECT: TokenType.SELECT,
  FROM: TokenType.FROM,
  WHERE: TokenType.WHERE,
  INSERT: TokenType.INSERT,
  INTO: TokenType.INTO,
  UPDATE: TokenType.UPDATE,
  DELETE: TokenType.DELETE,
  CREATE: TokenType.CREATE,
  DROP: TokenType.DROP,
  ALTER: TokenType.ALTER,
  TABLE: TokenType.TABLE,
  ADD: TokenType.ADD,
  COLUMN: TokenType.COLUMN,
  INDEX: TokenType.INDEX,
  JOIN: TokenType.JOIN,
  LEFT: TokenType.LEFT,
  RIGHT: TokenType.RIGHT,
  INNER: TokenType.INNER,
  OUTER: TokenType.OUTER,
  CROSS: TokenType.CROSS,
  ON: TokenType.ON,
  AND: TokenType.AND,
  OR: TokenType.OR,
  NOT: TokenType.NOT,
  IN: TokenType.IN,
  BETWEEN: TokenType.BETWEEN,
  LIKE: TokenType.LIKE,
  IS: TokenType.IS,
  NULL: TokenType.NULL,
  AS: TokenType.AS,
  ORDER: TokenType.ORDER,
  BY: TokenType.BY,
  GROUP: TokenType.GROUP,
  HAVING: TokenType.HAVING,
  LIMIT: TokenType.LIMIT,
  OFFSET: TokenType.OFFSET,
  ASC: TokenType.ASC,
  DESC: TokenType.DESC,
  VALUES: TokenType.VALUES,
  SET: TokenType.SET,
  DISTINCT: TokenType.DISTINCT,
  ALL: TokenType.ALL,
  TRUE: TokenType.TRUE,
  FALSE: TokenType.FALSE,
  IF: TokenType.IF,
  EXISTS: TokenType.EXISTS,
  PRIMARY: TokenType.PRIMARY,
  KEY: TokenType.KEY,
  AUTO_INCREMENT: TokenType.AUTO_INCREMENT,
  AUTOINCREMENT: TokenType.AUTO_INCREMENT,
  UNIQUE: TokenType.UNIQUE,
  DEFAULT: TokenType.DEFAULT,
  REFERENCES: TokenType.REFERENCES,
  FOREIGN: TokenType.FOREIGN,
  CONSTRAINT: TokenType.CONSTRAINT,
  CHECK: TokenType.CHECK,
  INTEGER: TokenType.INTEGER,
  INT: TokenType.INT,
  BIGINT: TokenType.BIGINT,
  SMALLINT: TokenType.SMALLINT,
  TINYINT: TokenType.TINYINT,
  FLOAT: TokenType.FLOAT,
  DOUBLE: TokenType.DOUBLE,
  DECIMAL: TokenType.DECIMAL,
  NUMERIC: TokenType.NUMERIC,
  REAL: TokenType.REAL,
  TEXT: TokenType.TEXT,
  VARCHAR: TokenType.VARCHAR,
  CHAR: TokenType.CHAR,
  BLOB: TokenType.BLOB,
  BOOLEAN: TokenType.BOOLEAN,
  BOOL: TokenType.BOOL,
  DATE: TokenType.DATE,
  TIME: TokenType.TIME,
  DATETIME: TokenType.DATETIME,
  TIMESTAMP: TokenType.TIMESTAMP,
  COUNT: TokenType.COUNT,
  SUM: TokenType.SUM,
  AVG: TokenType.AVG,
  MIN: TokenType.MIN,
  MAX: TokenType.MAX,
  COALESCE: TokenType.COALESCE,
  NULLIF: TokenType.NULLIF,
  CASE: TokenType.CASE,
  WHEN: TokenType.WHEN,
  THEN: TokenType.THEN,
  ELSE: TokenType.ELSE,
  END: TokenType.END,
  CAST: TokenType.CAST,
  UPPER: TokenType.UPPER,
  LOWER: TokenType.LOWER,
  LENGTH: TokenType.LENGTH,
  TRIM: TokenType.TRIM,
  SUBSTR: TokenType.SUBSTR,
  SUBSTRING: TokenType.SUBSTRING,
  CONCAT: TokenType.CONCAT,
  REPLACE: TokenType.REPLACE,
  NOW: TokenType.NOW,
  CURRENT_TIMESTAMP: TokenType.CURRENT_TIMESTAMP,
  CURRENT_DATE: TokenType.CURRENT_DATE,
  CURRENT_TIME: TokenType.CURRENT_TIME,
};
